"""Stable graph contract shared by topology, query, and orchestration layers."""
from __future__ import annotations
from typing import Protocol
from .models import GraphEdge, GraphNode, GraphPath, GraphResult

__all__ = ["GraphStore", "GraphNode", "GraphEdge", "GraphPath", "GraphResult"]


class GraphStore(Protocol):
    def add_node(self, node: GraphNode) -> None: ...
    def add_edge(self, edge: GraphEdge) -> None: ...
    def get_node(self, node_id: str) -> GraphNode | None: ...
    def get_edge(self, source: str, target: str, relationship: str | None = None) -> GraphEdge | None: ...
    def get_edges(self, source: str | None = None, target: str | None = None, relationship: str | None = None) -> list[GraphEdge]: ...
    def get_neighbors(self, node_id: str, relationship: str | None = None) -> list[GraphNode]: ...
    def downstream(self, node_id: str, max_depth: int | None = None) -> list[list[str]]: ...
    def upstream(self, node_id: str, max_depth: int | None = None) -> list[list[str]]: ...
    def paths_between(self, source: str, target: str, max_depth: int | None = None) -> list[list[str]]: ...
    def downstream_paths(self, node_id: str, max_depth: int | None = None) -> list[GraphPath]: ...
    def upstream_paths(self, node_id: str, max_depth: int | None = None) -> list[GraphPath]: ...
    def paths_between_detailed(self, source: str, target: str, max_depth: int | None = None) -> list[GraphPath]: ...
    def subgraph(self, node_ids: list[str]) -> GraphStore: ...
    def all_nodes(self) -> list[GraphNode]: ...
    def all_edges(self) -> list[GraphEdge]: ...
    def to_dict(self, document_id: str) -> dict: ...
