"""GraphStore boundary for HRIDAY.

Concrete storage implementations must live behind this interface so the
query layer never depends directly on a graph library or database.
"""
from __future__ import annotations

from typing import Any, Iterable, Protocol


class GraphStore(Protocol):
    def add_node(self, node_id: str, **attributes: Any) -> None: ...

    def add_edge(self, source: str, target: str, **attributes: Any) -> None: ...

    def get_node(self, node_id: str) -> dict[str, Any] | None: ...

    def get_neighbors(self, node_id: str) -> Iterable[str]: ...

    def downstream(self, node_id: str, depth: int | None = None) -> list[list[str]]: ...

    def upstream(self, node_id: str, depth: int | None = None) -> list[list[str]]: ...

    def shortest_path(self, source: str, target: str) -> list[str] | None: ...

    def get_edge(self, source: str, target: str) -> dict[str, Any] | None: ...

    def health(self) -> dict[str, Any]: ...
